branch-defaults:
  invite_users:
    environment: null
    group_suffix: null
global:
  application_name: Joinify
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
