# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb563b8b4e6d7ab6a5cc764ac75e6a59c8bacc8c4b4b07bb4b48746bb244a4dded6e505694c56eb8106667c4f83ff5d2b02a54f2360ef4f7f07a857630817642

test:
  secret_key_base: d682cd5b41ffca08878c4fa25eb4bfb916abe8b8f084f2206dfd052191084ed16aa29ebd84811e204499f5479a2980cb82ff500aa3184f85eadf7b3743151bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
